# # general settings
# name: Inpainting_Restormer_v2
# model_type: ImageCleanModel
# scale: 1
# num_gpu: 8  # set num_gpu: 0 for cpu mode
# manual_seed: 100

# # dataset and data loader settings
# datasets:
#   train:
#     name: TrainSet
#     type: Dataset_PairedImage
#     dataroot_gt: /content/drive/Shareddrives/HCMUT/Thesis/data/places265/village/target/train
#     dataroot_lq: /content/drive/Shareddrives/HCMUT/Thesis/data/places265/village/input/train
#     geometric_augs: true

#     filename_tmpl: '{}'
#     io_backend:
#       type: disk

#     # data loader
#     use_shuffle: true
#     num_worker_per_gpu: 8
#     batch_size_per_gpu: 8

#     ### -------------Progressive training--------------------------
#     mini_batch_sizes: [8,5,4,2,1,1]             # Batch size per gpu   
#     iters: [92000,64000,48000,36000,36000,24000]
#     gt_size: 384   # Max patch size for progressive training
#     gt_sizes: [128,160,192,256,320,384]  # Patch sizes for progressive training.
#     ### ------------------------------------------------------------

#     ### ------- Training on single fixed-patch size 128x128---------
#     # mini_batch_sizes: [8]   
#     # iters: [300000]
#     # gt_size: 128   
#     # gt_sizes: [128]
#     ### ------------------------------------------------------------

#     dataset_enlarge_ratio: 1
#     prefetch_mode: ~

#   val:
#     name: ValSet
#     type: Dataset_PairedImage
#     dataroot_gt: /content/drive/Shareddrives/HCMUT/Thesis/data/places265/village/target/val
#     dataroot_lq: /content/drive/Shareddrives/HCMUT/Thesis/data/places265/village/input/val
#     io_backend:
#       type: disk

# # network structures
# network_g:
#   type: Restormer
#   inp_channels: 3
#   out_channels: 3
#   dim: 48
#   num_blocks: [4,6,6,8]
#   num_refinement_blocks: 4
#   heads: [1,2,4,8]
#   ffn_expansion_factor: 2.66
#   bias: False
#   LayerNorm_type: WithBias
#   dual_pixel_task: False


# # path
# path:
#   pretrain_network_g: /content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer/best_checkpoint/deraining.pth #/content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer/best_checkpoint/net_g_latest-psnr-29.pth
#   strict_load_g: true
#   resume_state: ~
#   root: /content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer
#   # experiments_root: /content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer/experiments/Inpainting_Restormer
#   # models: /content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer/experiments/Inpainting_Restormer/models
#   # training_states: /content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer/experiments/Inpainting_Restormer/training_states
#   # visualization: /content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer/experiments/Inpainting_Restormer/visualization

# # training settings
# train:
#   total_iter: 300000
#   warmup_iter: -1 # no warm up
#   use_grad_clip: true

#   # Split 300k iterations into two cycles. 
#   # 1st cycle: fixed 3e-4 LR for 92k iters. 
#   # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
#   scheduler:
#     type: CosineAnnealingRestartCyclicLR
#     periods: [92000, 208000]         
#     restart_weights: [1,1]
#     eta_mins: [0.0003,0.000001]   
  
#   mixing_augs:
#     mixup: false
#     mixup_beta: 1.2
#     use_identity: true

#   optim_g:
#     type: AdamW
#     lr: !!float 3e-4
#     weight_decay: !!float 1e-4
#     betas: [0.9, 0.999]
  
#   # losses
#   pixel_opt:
#     type: L1Loss
#     loss_weight: 1
#     reduction: mean

# # validation settings
# val:
#   window_size: 8
#   val_freq: !!float 4e1
#   save_img: false
#   rgb2bgr: true
#   use_image: true
#   max_minibatch: 8

#   metrics:
#     psnr: # metric name, can be arbitrary
#       type: calculate_psnr
#       crop_border: 0
#       test_y_channel: true

# # logging settings
# logger:
#   print_freq: 1000
#   save_checkpoint_freq: !!float 4e1
#   use_tb_logger: true
#   wandb:
#     project: ~
#     resume_id: ~

# # dist training settings
# dist_params:
#   backend: nccl
#   port: 29500
name: Inpainting_Restormer_v3
model_type: ImageCleanModel
scale: 1
num_gpu: 4
manual_seed: 100
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: /content/drive/Shareddrives/HCMUT/Thesis/data/places265/village/target/train
    dataroot_lq: /content/drive/Shareddrives/HCMUT/Thesis/data/places265/village/input/train
    geometric_augs: True
    filename_tmpl: {}
    io_backend:
      type: disk
    
    use_shuffle: True
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    mini_batch_sizes: [8, 5, 4, 2, 1, 1]
    iters: [920, 640, 480, 360, 360, 240]
    gt_size: 384
    gt_sizes: [128, 160, 192, 256, 320, 384]
    dataset_enlarge_ratio: 1
    prefetch_mode: None
    phase: train
    scale: 1
  
  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: /content/drive/Shareddrives/HCMUT/Thesis/data/places265/village/target/val
    dataroot_lq: /content/drive/Shareddrives/HCMUT/Thesis/data/places265/village/input/val
    io_backend:
      type: disk
    
    phase: val
    scale: 1
  

network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False

path:
  pretrain_network_g: /content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer/best_checkpoint/deraining.pth #/content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer/best_checkpoint/net_g_latest-psnr-29.pth
  strict_load_g: true
  resume_state: ~
  root: /content/drive/Shareddrives/HCMUT/Thesis/checkpoint/restormer
  # experiments_root: /content/Restormer_original_training/experiments/Deraining_Restormer
  # models: /content/Restormer_original_training/experiments/Deraining_Restormer/models
  # training_states: /content/Restormer_original_training/experiments/Deraining_Restormer/training_states
  # log: /content/Restormer_original_training/experiments/Deraining_Restormer
  # visualization: /content/Restormer_original_training/experiments/Deraining_Restormer/visualization

train:
  total_iter: 3000
  warmup_iter: -1
  use_grad_clip: True
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [920, 2080]
    restart_weights: [1, 1]
    eta_mins: [0.0003, 1e-06]
  
  mixing_augs:
    mixup: False
    mixup_beta: 1.2
    use_identity: True
  
  optim_g:
    type: AdamW
    lr: 0.0003
    weight_decay: 0.0001
    betas: [0.9, 0.999]
  
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean
  

val:
  window_size: 8
  val_freq: 40.0
  save_img: False
  rgb2bgr: True
  use_image: True
  max_minibatch: 8
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: True
    ]
  ]
]
logger:
  print_freq: 1000
  save_checkpoint_freq: 40.0
  use_tb_logger: True
  wandb:
    project: None
    resume_id: None
  

dist_params:
  backend: nccl
  port: 29500

is_train: True
dist: True
rank: 0
world_size: 1
